name = "ai-accountability-coach"
main = "src/index.ts"
compatibility_date = "2026-04-16"

[observability]
enabled = true

[triggers]
crons = ["30 3 * * *", "30 15 * * *", "30 13 * * SUN"]

[[d1_databases]]
binding = "DB"
database_name = "ai-accountability-coach"
database_id = "66515eb5-4f9b-400f-aeae-2133d83bcfcf"
migrations_dir = "migrations"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true
